# Generated by Django 4.1.1 on 2023-01-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Climb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rating", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=250)),
                ("location", models.TextField(max_length=250)),
                ("people", models.IntegerField()),
            ],
        ),
    ]
