# Generated by Django 4.1.1 on 2023-02-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="climb",
            old_name="people",
            new_name="attempt",
        ),
    ]
