# Generated by Django 4.1.1 on 2023-02-07 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_rename_people_climb_attempt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="climb",
            old_name="attempt",
            new_name="attempts",
        ),
    ]
